const postgres = require('postgres');

(async () => {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    console.error('DATABASE_URL not set in environment.');
    process.exit(1);
  }

  const sql = postgres(connectionString, { prepare: false });

  try {
    const rows = await sql`
      SELECT column_default
      FROM information_schema.columns
      WHERE table_name = 'posts' AND column_name = 'reading_time_min'
    `;

    console.log('current default:', rows[0] && rows[0].column_default);

    if (rows[0] && rows[0].column_default && rows[0].column_default.includes('nextval')) {
      console.log('Dropping existing serial/default generated by SERIAL...');
      await sql`ALTER TABLE posts ALTER COLUMN reading_time_min DROP DEFAULT`;
    }

    console.log('Ensuring column is integer type...');
    await sql`ALTER TABLE posts ALTER COLUMN reading_time_min TYPE integer USING reading_time_min::integer`;

    console.log('Setting DEFAULT 1...');
    await sql`ALTER TABLE posts ALTER COLUMN reading_time_min SET DEFAULT 1`;

    console.log('Done.');
  } catch (err) {
    console.error('Error:', err);
    process.exit(1);
  } finally {
    await sql.end();
  }
})();
